### ISSUE TITLE
Issue with NameSpace dsig on Signature tab

### ISSUE THREAD

**Issue by SoodS** [onelogin/ruby-saml-example#10]
Hi,

We are integrating with OAM(Oracle Access Manager) using ruby-saml (1.0.0) and we are having difficulties parsing SAML response coming back from OAM.

When we are trying to verify signature file at file lib/xml_security.rb:253 (code snippet as below)
# verify signature
      signed_info_element = REXML::XPath.first(
        @sig_element,
        "//ds:SignedInfo",
        {"ds"=>DSIG}
      )

its returning as nil and if I remove variable (i.e. {"ds"=>DSIG}) from this line its returns correct value.
Same issue we are getting on line 295 of same file 
base64_signature = REXML::XPath.first(
        @sig_element,
        "//ds:SignatureValue"
      ).text
Every other place it is working perfectly fine. dsig name space is mentioned in parent tab of xml as 
< samlp:Response xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"
                **xmlns:dsig="http://www.w3.org/2000/09/xmldsig#"**
                xmlns:enc="http://www.w3.org/2001/04/xmlenc#"
                xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion"
                xmlns:x500="urn:oasis:names:tc:SAML:2.0:profiles:attribute:X500"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                Destination="http://localhost:3000/saml/acs"
                ID="id-1ita1C4y-cfGr3wtovKhVPPfUo45HVmKmEpdZX7o"
                InResponseTo="_75fb8af0-08ae-0133-f14b-28206648c607"
                IssueInstant="2015-07-09T21:22:14Z"
                Version="2.0"
                >

Are we missing something is settings or we are doing something wrong?
I am new to ruby so if something is missing here please let me know. Thanks in advance.
-Samar

**Comment by pitbulk** [comment]
Can you provide an example of the whole SAMLResponse?

**Comment by SoodS** [comment]
We added x509certificate after reading that issue. This issue is coming even after adding x509 certificate 
Here is sample SAML response

https://docs.google.com/document/d/1vaqCpYAyw9A57f9rvdogya6rOg-XZRlZGS18OQJP54Y/edit?usp=sharing

**Comment by tscoggins** [comment]
I think this issue is coming up because the signature element is being removed from the document in xml_security#validate_signature

    @sig_element ||= begin 
      element = REXML::XPath.first(
      @working_copy, 
      "//ds:Signature",
      {"ds"=>DSIG}
    )
    element.remove
    end

What is the reason the signature element is being removed?

**Comment by SoodS** [comment]
@pitbulk any suggestion to fix this issue.

**Comment by pitbulk** [comment]
@SoodS and @tscoggins can you review if this branch solves your issue:
https://github.com/onelogin/ruby-saml/pull/255

**Comment by SoodS** [comment]
Thanks @pitbulk for all your efforts. This branch works for us.

**Comment by SoodS** [comment]
@pitbulk  These changes works for us. Please get these into master.

**Comment by Vsandhya11** [comment]
I am getting this following error while validating XML

**SAML Response invalid
Invalid SAML Response. Not match the saml-schema-protocol-2.0.xsd**

**Comment by pitbulk** [comment]
@Vsandhya11 paste the XML at https://www.samltool.com/validate_xml.php and select as XSD the SAMLResponse. You will find the cause why the SAMLResponse is consider invalid.

**Comment by Vsandhya11** [comment]
@pitbulk I have done that and I got below error

Line: 7 | Column: 0  --> Element '{urn:oasis:names:tc:SAML:2.0:assertion}AttributeStatement': Missing child element(s). Expected is one of ( {urn:oasis:names:tc:SAML:2.0:assertion}Attribute, {urn:oasis:names:tc:SAML:2.0:assertion}EncryptedAttribute ).

Thank you for your prompt reply.

**Comment by pitbulk** [comment]
There you are, you have a SAMLResponse that contains an Assertion with a AttributeStatement, and inside it was Expected an Attribute ir an EncryptedAttribute but none was found. So the SAMLResponse is not valid.

**Comment by Vsandhya11** [comment]
@pitbulk, Thank you so much for your help. That helped me.

**Comment by Vsandhya11** [comment]
@pitbulk,  Is there any way I can ignore this attribute **<ns1:AttributeStatement/>** from the response before validating or if it's fails to validate using xsd, what are the best alternates?
