### ISSUE TITLE
KeyDescriptor use="encryption" is not coming into SP metadata

### ISSUE THREAD

**Issue by SoodS** [onelogin/ruby-saml-example#9]
I am trying to integrate one of our organization Ruby app with Oracle Access Mnager and SAML 2.0.
I am able to generate SP metadta which have KeyDescriptor use="signing" but  KeyDescriptor use="encryption" is missing. I am not able to see any method in Metadata class which generate KeyDescriptor with "encryption". We use to have both KeyDescriptiors when Integrating java app with Spring Security.

Also can we add more then one name_identified_format in SP metadata.

-Samar

**Comment by pitbulk** [comment]
The ruby SAML toolkit still does not support encryption, that is why not appear in the XML metadata.

**Comment by pitbulk** [comment]
We added the encryption KeyDescriptor:
https://github.com/onelogin/ruby-saml/blob/master/lib/onelogin/ruby-saml/metadata.rb#L36

Will be available in the next release of ruby-saml (1.0.0)
